#.github/workflows/scheduled-run.yml

name:  Run daily-update.py once each day after the 6 am liveocean build

on:
  schedule:
    - cron: '25 * * * *'   # run cron job at min hr * * *
jobs:
  build:
    name:  Trigger liveocean update
    runs-on: Ubuntu-latest
    steps:
      - name:  setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: check out repository code
        uses: actions/checkout@v2
        
      - name: execute py script
        run:
          python daily-update.py
